Unified Build error in WebProcessActivityState.cpp https://bugs.webkit.org/show_bug.cgi?id=314415 rdar://176570575
Reviewed by Pascoe.

While adding new files for https://bugs.webkit.org/show_bug.cgi?id=314409
I ran into a build failure caused by re-ordering unified sources

Source/WebKit/UIProcess/WebProcessActivityState.cpp:161:14: error: no member named 'numberOfProcessorCores' in namespace 'WTF'

WebProcessActivityState.cpp needs a #include <wtf/NumberOfCores.h>

* Source/WebKit/UIProcess/WebProcessActivityState.cpp:

Canonical link: https://commits.webkit.org/312939@main