[TestWebKitAPI] macCatalyst build is broken (FullscreenVideoTextRecognition.mm:184:11: error: instance method '-sendKey:code:isDown:modifiers:' not found) https://bugs.webkit.org/show_bug.cgi?id=314042 rdar://176228203
Reviewed by Aditya Keerthi.

Use PLATFORM(IOS_FAMILY) instead of PLATFORM(IOS) so macCatalyst takes
the UIKit fullscreen exit path rather than the AppKit path, which uses
-sendKey:code:isDown:modifiers: (which is not available on macCatalyst).

* Tools/TestWebKitAPI/Tests/WebKit/WKWebView/FullscreenVideoTextRecognition.mm:
(-[FullscreenVideoTextRecognitionWebView dismissFullscreen]):

Canonical link: https://commits.webkit.org/312676@main