[TestWebKitAPI] macCatalyst build is broken (TestWebKitAPI.swift:73:9: error: cannot find 'UINSApplicationInstantiate' in scope) https://bugs.webkit.org/show_bug.cgi?id=313873 rdar://176071541
Reviewed by Richard Robinson.

TestWebKitAPI.swift was calling UINSApplicationInstantiate() under
`#if WTF_PLATFORM_MACCATALYST`, but never imported the module exposing
it. The module map maps Helpers/ios/UIKitMacHelperSPI.h to submodule
TestWebKitAPILibrary.Helpers.ios.UIKitMacHelperSPI. This patch adds a
conditional import to work around the build fail.

We also apply the Swift-Cxx interop settings to the base config under
TWKAPI, so that other test targets (like TestWTF and TestIPC) can pick
them up.

* Tools/TestWebKitAPI/Configurations/Base.xcconfig:
* Tools/TestWebKitAPI/Configurations/TestWTF.xcconfig:
* Tools/TestWebKitAPI/Configurations/TestWebKitAPI.xcconfig:
* Tools/TestWebKitAPI/Runner/TestWebKitAPI.swift:

Canonical link: https://commits.webkit.org/312706@main