[TestWebKitAPI] macCatalyst build is broken (FontAttributes.mm:64:89: error: 'objectForKey:' is unavailable: not available on macCatalyst) https://bugs.webkit.org/show_bug.cgi?id=314043 rdar://176228243
Reviewed by Aditya Keerthi.

Cast the font to CocoaFont before calling -fontDescriptor so the compiler
resolves to the platform-appropriate descriptor type rather than picking
the unavailable NSFontDescriptor overload from an untyped receiver.

* Tools/TestWebKitAPI/Tests/WebKit/WKWebView/FontAttributes.mm:
(-[FontTextStyleUIDelegate _webView:didChangeFontAttributes:]):

Canonical link: https://commits.webkit.org/312657@main